GLOBAL.Mimetypes={
        "audio/basic" : ".au",
        "video/msvideo" : ".avi",
        "video/avi" : ".avi",
        "video/x-msvideo" : ".avi",
        "image/bmp" : ".bmp",
        "application/x-bzip2" : ".bz2",
        "text/css" : ".css",
        "application/xml-dtd" : ".dtd",
        "application/msword" : ".doc",
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document" : ".docx",
        "application/vnd.openxmlformats-officedocument.wordprocessingml.template" : ".dotx",
        "application/ecmascript" : ".es",
        "application/octet-stream" : ".exe",
        "image/gif" : ".gif",
        "application/x-gzip" : ".gz",
        "application/mac-binhex40" : ".hqx",
        "text/html" : ".html",
        "application/java-archive" : ".jar",
        "image/jpg" : ".jpg",
        "image/jpeg" : ".jpeg",
        "application/x-javascript" : ".js",
        "audio/x-midi" : ".midi",
        "audio/mpeg" : ".mp3",
        "video/mpeg" : ".mpeg",
        "audio/vorbis, application/ogg" : ".ogg",
        "application/pdf" : ".pdf",
        "application/x-perl" : ".pl",
        "image/png" : ".png",
        "application/vnd.openxmlformats-officedocument.presentationml.template" : ".potx",
        "application/vnd.openxmlformats-officedocument.presentationml.slideshow" : ".ppsx",
        "application/vnd.ms-powerpoint" : ".ppt",
        "application/vnd.openxmlformats-officedocument.presentationml.presentation" : ".pptx",
        "application/postscript" : ".ps",
        "video/quicktime" : ".qt",
        "audio/x-pn-realaudio" : [".ra",".ram"],
        "audio/vnd.rn-realaudio" : [".ra",".ram"],
        //"audio/x-pn-realaudio" : ".ram",
        //"audio/vnd.rn-realaudio" : ".ram",
        "application/rdf" : ".rdf",
        "application/rdf+xml" : ".rdf",
        "application/rtf" : ".rtf",
        "text/sgml" : ".sgml",
        "application/x-stuffit" : ".sit",
        "application/vnd.openxmlformats-officedocument.presentationml.slide" : ".sldx",
        "image/svg+xml" : ".svg",
        "application/x-shockwave-flash" : ".swf",
        "application/x-tar" : ".tar.gz",
        "application/x-tar" : ".tgz",
        "image/tiff" :".tiff",
        "text/tab-separated-values" : ".tsv",
        "text/plain" :".txt",
        "audio/wav, audio/x-wav" :".wav",
        "application/vnd.ms-excel.addin.macroEnabled.12" : ".xlam",
        "application/vnd.ms-excel" : ".xls",
        "application/vnd.ms-excel.sheet.binary.macroEnabled.12" : ".xlsb",
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" :".xlsx",
        "application/vnd.openxmlformats-officedocument.spreadsheetml.template" : ".xltx",
        "application/xml" : ".xml",
        "application/zip" : ".zip",
        "application/x-compressed-zip" : ".zip"

};